### ISSUE TITLE
All stars have radius of 0.98

### ISSUE THREAD

**Issue by elisabethadams** [timothydmorton/isochrones#52]
(Well, they probably don't actually.)

But the following instructions result in essentially the same values for Teff from 3000-7000:

```
mist = MIST_Isochrone()
model  = StarModel(mist, Teff=(5770, 80), logg=(4.44, 0.08), feh=(0.,0.1))
model.fit()
model.samples['radius_0_0'].quantile([0.15,0.5,0.85])


0.15    0.922251
0.50    0.982562
0.85    1.064326

**Comment by timothydmorton** [comment]
The secret of the universe has been discovered!

Two possible thoughts:
* Is the `model.fit()` call actually running a new fit every time, or is it reading the results of an old fit?  
* Are you changing Teff but leaving `logg = (4.44, 0.08)`?  If so, then the logg constraint might dominate over the Teff?

**Comment by elisabethadams** [comment]
Definitely running a new model.fit() every time (the numbers change after the 3rd decimal place every time I run it).

Changing logg (and increasing the errors) doesn't really affect it:

```
model  = StarModel(mist, Teff=(3000,200), logg=(4.7, 0.28), feh=(0.,0.1))

0.15    0.921389
0.50    0.981665
0.85    1.061877

**Comment by timothydmorton** [comment]
That's definitely not right...do the new fits take time to run? What if you call `model.fit(refit=True)`?  You're using v1.0, right?

**Comment by timothydmorton** [comment]
(in other words I wonder whether the differences are just from choosing different numbers of random samples from the already-run multinest chains)

**Comment by elisabethadams** [comment]
Hmm, the refit=True may have done the trick! Why is refit=False the default?

**Comment by timothydmorton** [comment]
In my use, it's much more common for me to want to quickly pull up the results of an already-fit model than to change the parameters of a model and then refit.  You can avoid this kind of problem by giving your `StarModel`s names (use the `name=` keyword), because that will define what the multinest chains are called, and thus you won't have clashing fit files.  

There is definitely an area that needs improvement!  Thanks for bringing it to my attention.
